### ISSUE TITLE
Why sessions ?

### ISSUE THREAD

**Issue by smartcris** [yunjiali/sails-waterlock-jwt-template#2]
I confess I'm a bit more comfortable on client side Javascript, but I don't understand why is it necessary to use sessions with tokens.
Can I use this API to serve an Android or IOS app ?
Thx.

**Comment by yunjiali** [comment]
Well, you don't have to use token honestly. There are pros and cons about token based authentication and here is a very good article to explain it:

https://scotch.io/tutorials/the-ins-and-outs-of-token-based-authentication

Regarding Android and iOS app, yes, definitely you can use http call to get data from this server.

**Comment by smartcris** [comment]
Ok, thank you for the link, but...... I still don't understand why you use server side sessions  to check the admin roles.

` if (req.session.user.role !== 'admin'){
        return res.forbidden('You are not permitted to perform this action.');
    }`

Wouldn't be better to check if the token belong to an admin user ?

**Comment by yunjiali** [comment]
Yes, you are absolutely right. I didn't think about that :=(.  So we can create a new policy maybe called hasAdminJsonWebToken and reuse the code in hasJsonWebToken.js. 

```
waterlock.validator.validateTokenRequest(req, function(err, user){
    if(err || user.role !=='admin'){
      return res.forbidden(err);  
    }

    // valid request
    next();
  });
```
Does this fit your requirement?

**Comment by smartcris** [comment]
Clean and simple.
I have another question about the user model, suppose I added some other attributes to that model, for example firstname, lastname, username etc. How can I permit a simple user to update his own user profile, without giving him an admin role?

**Comment by yunjiali** [comment]
I usually use policy to regulate such action. For example, you can create a isOwner.js policy to check whether the id of the user you want to change is the same as the id of the owner of the token, something similar to:

```user.id === param('id')```

**Comment by smartcris** [comment]
In this way he could change his own role to admin. What do you think is a good way to add a policy to a controller action that goes deep and restrict access to a single model attribute?

**Comment by yunjiali** [comment]
I think there is no such way out-of-box at the moment. In my opinion, there are two ways to deal with this problem. You either re-develop the 'update' methods and restrict the access of a certain attribute programmatically. For example, in the User model, add a before updating method, checking whether the user is admin. If not, the action is denied. You can also do that in the UserController. Another way is, you can create a separate model called AdminUser, which is only accessible by AdminUser.

**Comment by smartcris** [comment]
Thx for the suggestions. Appreciate your help!
